// Writes a song model out as Strudel code, laid out like a hand-written
// piece: harmony, drums, instruments, melodies, sections, then the
// arrangement. The output pastes straight into strudel.cc.

import { chordName, keyName } from './theory.js';
import { bassScale, renderScales } from './bass.js';
import { melodyScale, renderKeyMelody, renderSolo } from './melody.js';
import { DRUM_BREAK_PARTS, FEEL_TO_GROOVE, GROOVES, HELPERS } from './drums.js';

const RULE = '// ' + '='.repeat(58);
const heading = (title) => `${RULE}\n// ${title}\n${RULE}`;

// "<a b c d>" on one line, or one row per `perLine` items in backticks.
function seq(items, perLine = 4) {
  if (items.length <= perLine) return `"<${items.join(' ')}>"`;
  const rows = [];
  for (let i = 0; i < items.length; i += perLine) rows.push('  ' + items.slice(i, i + perLine).join(' '));
  return `\`<\n${rows.join('\n')}\n>\``;
}

function chordItems(bars, key) {
  return bars.map((bar) =>
    bar.length === 1 ? chordName(bar[0], key) : `[${bar.map((c) => chordName(c, key)).join(' ')}]`,
  );
}

function scaleItems(bars, key) {
  return renderScales(bars, key)
    .slice(1, -1)
    .match(/\[[^\]]+\]|\S+/g);
}

// Materials that reuse another's harmony variables.
const HARMONY_ALIAS = { outro: 'intro' };

const SECTION_NOTES = {
  intro: 'Intro',
  vamp: 'Vamp: the band comes in over a two-chord groove',
  verse: 'Verse',
  pre: 'Pre-chorus: building towards the hook',
  chorus: 'Chorus',
  riff: 'Horn riff',
  bridge: 'Bridge',
  drumBreak: 'Two bars of drums alone, with a bass pickup at the end',
  solo: 'Solo',
  solo2: 'Second solo',
  breakdown: 'Breakdown: claps, bass, choir and the hook',
  lift: 'Lift into the new key',
  outro: 'Outro: the intro comes back',
  finale: 'Final chord, built one instrument at a time',
};

export function renderSong(song) {
  const { style, form, materials: m, key, bpm, swing, seed } = song;
  const s = style.sounds;
  const out = [];
  const totalBars = form.reduce((n, x) => n + x.bars, 0);
  const keyScaleOf = (mat) => melodyScale(mat.key);

  // ---- Header ------------------------------------------------------
  out.push(
    `// "${song.title}": ${style.label.toLowerCase()} in ${keyName(key)}, ${bpm} BPM, ${totalBars} bars`,
    `// Generated by strudel-songsmith (seed "${seed}", style ${song.styleName})`,
    '',
    `setCpm(${bpm}/4)`,
    '',
    `const SWING = ${fmt(swing)}`,
    '',
  );

  // ---- Harmony -----------------------------------------------------
  out.push(heading('HARMONY: chord symbols + matching chord-scales'), '');
  const harmonyOrder = [
    'intro',
    'vamp',
    'verse',
    'pre',
    'chorus',
    'riff',
    'bridge',
    'solo',
    'solo2',
    'breakdown',
    'lift',
  ];
  for (const type of harmonyOrder) {
    const mat = m[type];
    if (!mat) continue;
    const note = harmonyNote(type, mat, song);
    if (note) out.push(`// ${note}`);
    out.push(`let ${type}Chords = chord(${seq(chordItems(mat.bars, mat.key))})`);
    out.push(`let ${type}Scales = ${seq(scaleItems(mat.bars, mat.key))}`, '');
  }

  // ---- Drums -------------------------------------------------------
  const grooves = new Set();
  for (const inst of form) {
    const feel = style.feels[inst.type];
    if (feel && !['drumBreak', 'finale'].includes(inst.type)) grooves.add(FEEL_TO_GROOVE[feel]);
  }
  out.push(heading('DRUMS'), '');
  for (const g of grooves) out.push(`let ${g} = ${GROOVES[g]}`, '');
  out.push(HELPERS, '');

  // ---- Instruments -------------------------------------------------
  out.push(heading('INSTRUMENTS\n// Harmony parts take a chord pattern; n() picks voicing notes'), '');
  out.push(instruments(style), '');

  // ---- Melodies ----------------------------------------------------
  out.push(heading('MELODIES (all degrees)'), '');
  const melodyNotes = {
    intro: 'Intro: the hook as a teaser',
    verse: `Verse, in ${keyName(key)}`,
    pre: 'Pre-chorus: the motif climbs as the harmony rises',
    chorus: 'THE HOOK: motifs repeat, moved to fit each chord',
    riff: 'Horn riff lead (harmonised a third below)',
    bridge: m.bridge ? `Bridge, in ${keyName(m.bridge.key)}` : '',
    breakdown: '',
  };
  for (const type of ['intro', 'verse', 'pre', 'chorus', 'riff', 'bridge']) {
    const mat = m[type];
    if (!mat?.melody) continue;
    if (melodyNotes[type]) out.push(`// ${melodyNotes[type]}`);
    out.push(`let ${type}Mel = ${seq(renderKeyMelody(mat.melody, mat.key), 1)}`, '');
  }
  if (m.chorus.answer && form.some((x) => x.type === 'chorus' && x.opts.answer)) {
    out.push('// Answers in the gaps the hook leaves');
    out.push(`let chorusAnswer = ${seq(renderKeyMelody(m.chorus.answer, key), 2)}`, '');
  }
  for (const type of ['solo', 'solo2']) {
    if (!m[type]) continue;
    out.push(`// ${type === 'solo' ? 'Solo' : 'Second solo'}, in chord-scale degrees two octaves above the bass`);
    out.push(`let ${type}Line = ${seq(renderSolo(m[type].solo), 1)}`, '');
  }
  if (m.lift)
    out.push('// Lift: a rising line into the new key', 'let liftMel = "<[0 [~ 1] 2 [~ 3]] [4 [~ 4] 5 ~]>"', '');

  // ---- Sections ----------------------------------------------------
  out.push(heading('SECTIONS'), '');
  const defined = new Set();
  for (const inst of form) {
    if (defined.has(inst.type)) continue;
    defined.add(inst.type);
    const instances = form.filter((x) => x.type === inst.type);
    const params = sectionParams(instances);
    const mat = m[inst.type];
    const { drums, pitched } = sectionParts(inst.type, inst, mat, song, params);
    const body = params.includes('key')
      ? stackCode([...drums, `stack(\n${indent(pitched.join(',\n'), 2)}\n).transpose(key)`])
      : stackCode([...drums, ...pitched]);
    out.push(`// ${SECTION_NOTES[inst.type]}`);
    if (params.length) {
      const defaults = params.map((p) => (p === 'key' ? 'key = 0' : `${p} = false`)).join(', ');
      out.push(`let ${inst.type} = ({ ${defaults} } = {}) => ${body}`, '');
    } else {
      out.push(`let ${inst.type} = ${body}`, '');
    }
  }

  // ---- Song --------------------------------------------------------
  out.push(heading(`THE SONG (${totalBars} bars)`), '');
  const rows = form.map((inst) => {
    const params = sectionParams(form.filter((x) => x.type === inst.type));
    if (!params.length) return `  [${inst.bars}, ${inst.type}]`;
    const args = [];
    if (inst.opts.second) args.push('second: true');
    if (inst.opts.answer) args.push('answer: true');
    if (inst.opts.big) args.push('big: true');
    if (inst.opts.shift) args.push(`key: ${inst.opts.shift}`);
    return `  [${inst.bars}, ${inst.type}(${args.length ? `{ ${args.join(', ')} }` : ''})]`;
  });
  out.push(`let song = [\n${rows.join(',\n')}\n]`, '');
  out.push('$: arrange(\n  ...song.map(([bars, section]) => [bars, section.swingBy(SWING, 8)])\n)', '');
  return out.join('\n');

  // ---- Section recipes --------------------------------------------
  function sectionParts(type, inst, mat, song, params) {
    const n = inst.bars;
    const groove = FEEL_TO_GROOVE[style.feels[type]];
    const hv = HARMONY_ALIAS[type] ?? type; // harmony variable prefix
    const C = `${hv}Chords`;
    const S = `${hv}Scales`;
    const bass = (extra = '') => `bass("${mat.bass.pattern}", ${S})${extra}`;
    const scale = mat ? keyScaleOf(mat) : '';
    const comp2 = style.sounds.comp2 !== 'none' ? `${style.sounds.comp2}(${C})` : null;
    const second = (code) => (params.includes('second') ? `second ? ${code} : silence` : null);
    const when = (flag, code) => (params.includes(flag) ? `${flag} ? ${code} : silence` : null);
    const keep = (parts) => parts.filter(Boolean);

    switch (type) {
      case 'intro':
      case 'outro': {
        const busy = inst.energy >= 0.5;
        const drums = keep([groove, type === 'outro' ? 'crashFirst(4)' : null]);
        const teaser = m.intro.melody ? `bell(line(introMel, "${keyScaleOf(m.intro)}", 12))` : null;
        return {
          drums,
          pitched: keep([
            busy ? `keys(${C})` : `${C}.voicing().sound("${s.keys}").gain(.32).room(.35)`,
            `strings(${C})`,
            `bass("${m.intro.bass.pattern}", ${S}).gain(.6)`,
            teaser,
          ]),
        };
      }
      case 'vamp':
        return {
          drums: [`${groove}.mask("<0 0 1 1>")`, 'fillLast(4)'],
          pitched: [bass(), `keys(${C}).lpf(saw.slow(4).range(700, 8000))`],
        };
      case 'verse':
        return {
          drums: keep([groove, second('s("~ ~ ~ [~ ~ ~ sd]").gain(.1)')]),
          pitched: keep([
            bass(),
            `keys(${C})`,
            comp2,
            `lead(line(verseMel, "${scale}"))`,
            second(`${style.sounds.extra}(${C})`),
            second(`pad(${C})`),
          ]),
        };
      case 'pre':
        return {
          drums: [groove, `fillLast(${n})`, `s("white").gain(saw.slow(${n}).range(0, .07)).hpf(3000)`],
          pitched: [
            bass(),
            `keys(${C}, "x*8")\n  .clip(.4)\n  .gain(.3)\n  .lpf(saw.slow(${n}).range(800, 7000))`,
            `pad(${C})`,
            `lead(line(preMel, "${scale}"))`,
          ],
        };
      case 'chorus':
        return {
          drums: [groove, `crashFirst(${n})`, `fillLast(${n})`],
          pitched: keep([
            bass(),
            `keys(${C}, "${style.comp.chorus}")${style.color === 0 ? '' : '.clip(.5).gain(.28)'}`,
            comp2,
            `pad(${C})`,
            `lead(line(chorusMel, "${scale}"))`,
            `double(line(chorusMel, "${scale}"))`,
            when('answer', `counter(line(chorusAnswer, "${scale}"))`),
            when('big', `stabs(${C})`),
            when('big', `strings(${C})`),
            when('big', `choir(${C})`),
          ]),
        };
      case 'riff':
        return {
          drums: [groove, 'crashFirst(4)', 'fillLast(4)'],
          pitched: keep([
            bass(),
            `hornSection(line(harmonize(riffMel, 2), "${scale}"))`,
            `keys(${C}).gain(.28)`,
            comp2,
          ]),
        };
      case 'bridge':
        return {
          drums: [groove],
          pitched: [
            bass('.gain(.65)'),
            `arp(${C})`,
            `strings(${C})`,
            `lead(line(bridgeMel, "${scale}"))`,
            `bell(line(bridgeMel, "${scale}", 12)).gain(.15)`,
          ],
        };
      case 'drumBreak': {
        const next = mat.pickupInto;
        return {
          drums: DRUM_BREAK_PARTS,
          pitched: [
            `bass("<~ [~ ~ ~ [-2 -1]]>", "${bassScale(next, m[mat.pickupFrom].key)}")${mat.pickupShift ? `.transpose(${mat.pickupShift})` : ''}`,
          ],
        };
      }
      case 'solo':
      case 'solo2': {
        const [sound, gain] = s.soloists[inst.opts.soloist % s.soloists.length];
        const bossa = type === 'solo2';
        return {
          drums: [groove, `crashFirst(${n})`, `fillLast(${n})`],
          pitched: keep([
            bass(),
            bossa ? `keys(${C}, "${style.comp.bossa}").gain(.26)` : `keys(${C}).gain(.3)`,
            bossa ? `strings(${C}).gain(.08)` : comp2,
            `line(${type}Line, ${S}, 24)\n  .sound("${sound}")\n  .gain(${fmt(gain)})\n  .room(.3)\n  .delay(.15)\n  .delaytime(.27)\n  .pan(${bossa ? '.42' : '.55'})`,
          ]),
        };
      }
      case 'breakdown': {
        const half = Math.floor(n / 2);
        const mask = `<${[...Array(half).fill(0), ...Array(n - half).fill(1)].join(' ')}>`;
        return {
          drums: [groove, `fillLast(${n})`],
          pitched: [
            bass('.gain(.6)'),
            `pad(${C}).gain(.18)`,
            `choir(${C})`,
            `keys(${C}, "${style.comp.chorus}")\n  .clip(.5)\n  .gain(.24)\n  .mask("${mask}")`,
            `lead(line(chorusMel, "${scale}"))`,
          ],
        };
      }
      case 'lift':
        return {
          drums: [groove, 'crashFirst(2)'],
          pitched: [bass(), `keys(${C}, "x*4").clip(.5).gain(.32)`, `hornSection(line(liftMel, ${S}, 36))`],
        };
      case 'finale':
        return finaleParts(mat, song);
      default:
        throw new Error(`No recipe for section ${type}`);
    }
  }

  function finaleParts(mat, song) {
    const chord = mat.bars[0][0];
    const name = chordName(chord, song.key);
    const scaleName = bassScale(chord, song.key).replace(/\d+:/, (o) => `${Number(o.slice(0, -1)) + 2}:`);
    const degrees =
      song.key.mode === 'minor'
        ? [4, 7, 9, 13, 15]
        : style.color === 2
          ? [4, 9, 13, 15, 17, 19]
          : style.color === 1
            ? [4, 7, 9, 11, 14]
            : [4, 7, 9, 11];
    const voices = [
      [s.lead[0], s.lead[1] * 0.6],
      ...s.soloists,
      [s.bell[0], s.bell[1]],
      [s.double[0], s.double[1] * 1.5],
    ];
    const enters = degrees.map((d, i) => {
      const [sound, gain] = voices[i % voices.length];
      return `line("[${'~ '.repeat(i + 1)}${d}@${7 - i}]", "${scaleName}").slow(2).sound("${sound}").gain(${fmt(gain * 0.75)}).room(.5)`;
    });
    return {
      drums: ['s("[bd,cr]").slow(2).gain(.55)', 's("rd*16").gain(.09).velocity(saw.slow(2).range(.3, 1))'],
      pitched: [
        `chord("${name}").voicing().slow(2).sound("${s.keys}").gain(.4).room(.5)`,
        `strings(chord("${name}")).slow(2)`,
        `bass("0", "${bassScale(chord, song.key)}").slow(2)`,
        ...enters,
      ],
    };
  }
}

function harmonyNote(type, mat, song) {
  const k = keyName(mat.key);
  switch (type) {
    case 'intro':
      return mat.planing
        ? 'Intro: add9 chords planing down in whole steps'
        : 'Intro: the first four bars of the chorus';
    case 'vamp':
      return `Vamp in ${k}`;
    case 'verse':
      return `Verse, ${mat.bars.length} bars`;
    case 'pre':
      return `Pre-chorus, ${mat.bars.length} bars`;
    case 'chorus':
      return mat.bars.length > 8 ? `Chorus: eight bars plus a ${mat.bars.length - 8}-bar tag` : 'Chorus';
    case 'riff':
      return 'Riff vamp';
    case 'bridge':
      return `Bridge in ${k}, with a cadence back home in the last two bars`;
    case 'solo':
    case 'solo2':
      return song.style.color === 2 && song.style.form !== 'jazz'
        ? 'Solo changes: ii-V pairs moving through keys, then home'
        : 'Solo changes';
    case 'breakdown':
      return 'Breakdown over the chorus changes';
    case 'lift':
      return `Lift: bVI to V of ${k}`;
    default:
      return '';
  }
}

// Which options a section's instances actually vary.
function sectionParams(instances) {
  const params = [];
  const type = instances[0].type;
  if (type === 'verse' && instances.some((x) => x.opts.second)) params.push('second');
  if (type === 'chorus' && instances.some((x) => x.opts.answer)) params.push('answer');
  if (type === 'chorus' && instances.some((x) => x.opts.big)) params.push('big');
  if (instances.some((x) => x.opts.shift)) params.push('key');
  return params;
}

function instruments(style) {
  const s = style.sounds;
  const rock = style.color === 0;
  const defs = [
    `let keys = (c, rhythm = "${style.comp.main}") =>
  c.struct(rhythm)
    .voicing()
    .sound("${s.keys}")
    .gain(${rock ? '.2' : '.34'})${rock ? '\n    .clip(.5)' : ''}
    .velocity(rand.range(.8, 1))
    .room(.2)`,
    `let arp = c =>
  n("[0 1 2 3]*2")
    .set(c)
    .voicing()
    .sound("${s.arp ?? s.keys}")
    .gain(.24)
    .room(.4)
    .delay(.2)
    .delaytime(.375)`,
  ];
  if (s.comp2 === 'clav')
    defs.push(`let clav = c =>
  n("[~ 0 ~ 2] [~ ~ 1 ~] [~ 0 ~ 2] [~ 3 ~ ~]")
    .set(c)
    .voicing()
    .sound("gm_clavinet")
    .gain(.19)
    .velocity(rand.range(.7, 1))
    .pan(.28)`);
  if (s.comp2 === 'strum')
    defs.push(`let strum = c =>
  c.struct("x [~ x] [~ x] [x x]")
    .voicing()
    .sound("${s.guitar}")
    .clip(.6)
    .gain(.22)
    .velocity(rand.range(.7, 1))
    .pan(.7)`);
  if (s.comp2 === 'organ')
    defs.push(`let organ = c => c.anchor("c5").voicing().sound("gm_drawbar_organ").gain(.08).pan(.3)`);
  if (s.extra === 'scratch')
    defs.push(`let scratch = c =>
  n("[0 ~ 0 2] [~ 1 ~ 0] [~ 0 2 ~] [1 ~ 0 ~]")
    .set(c)
    .voicing()
    .sound("${s.guitar}")
    .clip(.5)
    .gain(.28)
    .velocity(rand.range(.7, 1))
    .pan(.72)`);
  defs.push(
    `let pad = c => c.anchor("a4").voicing().sound("${s.pads[0]}").gain(.14).room(.4)
let strings = c => c.anchor("d6").voicing().sound("${s.pads[1]}").gain(.11).room(.45)
let choir = c => c.anchor("e5").voicing().sound("${s.pads[2]}").gain(.09).room(.45)`,
    `let stabs = c =>
  c.struct("x ~ ~ ~")
    .anchor("g5")
    .voicing()
    .sound("${s.horns[0]}")
    .clip(.3)
    .gain(.22)`,
    `// Bass: scale degrees against a chord-scale pattern
let bass = (degrees, scales) =>
  n(degrees)
    .scale(scales)
    .sound("${s.bass}")
    .clip(.8)
    .gain(.75)`,
    `// Melodic parts: degrees against a key or chord-scale,
// optionally shifted up from the bass register
let line = (degrees, scales, up = 0) => n(degrees).scale(scales).transpose(up)

// Diatonic harmony: the line plus copies a third / fifth below
let harmonize = (p, ...steps) => stack(p, ...steps.map(st => p.sub(st)))`,
    `let lead = p => p.sound("${s.lead[0]}").gain(${fmt(s.lead[1])}).room(.25)
let double = p => p.transpose(12).sound("${s.double[0]}").gain(${fmt(s.double[1])}).room(.35)
let counter = p => p.sound("${s.answer[0]}").gain(${fmt(s.answer[1])}).pan(.62).room(.25)
let bell = p => p.sound("${s.bell[0]}").gain(${fmt(s.bell[1])}).room(.4)`,
    `let hornSection = p => stack(
  p.sound("${s.horns[0]}").gain(.3),
  p.sound("${s.horns[1]}").gain(.18)
).room(.25)`,
  );
  return defs.join('\n\n');
}

function stackCode(parts) {
  return `stack(\n${indent(parts.join(',\n'), 2)}\n)`;
}

function indent(text, n) {
  const pad = ' '.repeat(n);
  return text
    .split('\n')
    .map((l) => pad + l)
    .join('\n');
}

// .5 rather than 0.5, as in hand-written Strudel.
function fmt(x) {
  const r = Math.round(x * 100) / 100;
  return String(r).replace(/^0\./, '.');
}

const WORDS_A = [
  'Velvet',
  'Midnight',
  'Copper',
  'Neon',
  'Golden',
  'Lazy',
  'Electric',
  'Paper',
  'Silver',
  'Crimson',
  'Hollow',
  'Sunday',
];
const WORDS_B = [
  'Groove',
  'Avenue',
  'Skyline',
  'Machine',
  'Harbour',
  'Lights',
  'Parade',
  'Static',
  'Garden',
  'Engine',
  'River',
  'Signal',
];

export function titleFor(seed) {
  let h = 0;
  for (const ch of String(seed)) h = (h * 31 + ch.charCodeAt(0)) >>> 0;
  return `${WORDS_A[h % WORDS_A.length]} ${WORDS_B[(h >>> 8) % WORDS_B.length]}`;
}
