// Style definitions: everything that differs between jazz-funk, pop,
// rock and jazz lives here as data, so new styles are mostly a matter
// of adding an entry.
//
// Templates are roman numerals, one token per bar; "[ii7 V7]" puts two
// chords in a bar. Numerals count on the major scale, so minor-key
// templates spell bIII, bVI and bVII. A template's length is its
// natural phrase; it is repeated to fill the section.

export const STYLES = {
  jazzfunk: {
    label: 'Jazz-funk',
    color: 2,
    reharm: 0.5,
    adventurous: 0.8,
    tempo: [100, 116],
    swing: [0.06, 0.12],
    modes: [['major', 1]],
    tonics: [5, 10, 3, 0, 7, 2],
    form: 'jazzfunk',
    approachChromatic: 0.75,
    templates: {
      major: {
        vamp: ['ii7 V7', 'ii7 [ii7 V7]', 'vi7 II7'],
        verse: [
          'vi7 II7 vi7 II7 IVmaj7 [iii7 bIII7] ii7 V7',
          'ii7 V7 iii7 VI7 ii7 V7 Imaj7 Imaj7',
          'Imaj7 vi7 ii7 V7 iii7 VI7 ii7 V7',
          'IVmaj7 iii7 ii7 Imaj7 IVmaj7 iii7 ii7 V7sus',
          'vi7 vi7 II7 II7 IVmaj7 iii7 ii7 V7',
        ],
        pre: ['ii7 iii7 iv7 #iv° V7sus V7', 'IVmaj7 #iv° V7sus V7', 'ii7 iii7 IVmaj7 V7sus'],
        chorus: [
          'IVmaj7 III7 vi7 [v7 I7] IVmaj7 III7 [vi7 II7] [ii7 V7]',
          'Imaj7 VI7 ii7 V7 iii7 VI7 ii7 V7',
          'IVmaj7 V7 iii7 vi7 ii7 V7 Imaj7 [ii7 V7]',
          'vi7 ii7 V7 Imaj7 IVmaj7 ii7 V7sus V7',
        ],
        tag: ['bVImaj7 V7sus', 'bVImaj7 bVII7'],
        bridge: ['IVmaj7 bVIImaj7 ii7 V7 Imaj7 IVmaj7', 'ii7 V7 Imaj7 vi7 ii7 V7', 'Imaj7 vi7 IVmaj7 V7 iii7 vi7'],
        riff: ['ii7 V7', 'vi7 II7'],
      },
    },
    feels: {
      intro: 'introRide',
      vamp: 'funk',
      verse: 'funk',
      pre: 'funk',
      chorus: 'disco',
      bridge: 'halfTime',
      solo: 'funk',
      solo2: 'bossa',
      riff: 'funk',
      breakdown: 'claps',
      lift: 'build',
      outro: 'introRide',
    },
    bassFeels: {
      intro: 'pedal',
      vamp: 'funk',
      verse: 'funk',
      pre: 'drive',
      chorus: 'disco',
      bridge: 'halfTime',
      solo: 'funk',
      solo2: 'bossa',
      riff: 'funk',
      breakdown: 'disco',
      lift: 'disco',
      outro: 'pedal',
    },
    comp: { main: '~ [~ x] ~ [~ ~ x ~]', chorus: '[~ x]*4', bossa: '[x ~ ~ x] [~ ~ x ~] [~ x ~ ~] [x ~ ~ ~]' },
    sounds: {
      keys: 'gm_epiano1',
      comp2: 'clav',
      extra: 'scratch',
      guitar: 'gm_electric_guitar_muted',
      pads: ['gm_voice_oohs', 'gm_string_ensemble_1', 'gm_choir_aahs'],
      lead: ['gm_alto_sax', 0.5],
      double: ['gm_flute', 0.13],
      answer: ['gm_trumpet', 0.3],
      bell: ['gm_vibraphone', 0.3],
      soloists: [
        ['gm_overdriven_guitar', 0.34],
        ['gm_vibraphone', 0.42],
        ['gm_tenor_sax', 0.45],
        ['gm_trumpet', 0.36],
      ],
      horns: ['gm_brass_section', 'gm_alto_sax'],
      bass: 'gm_electric_bass_finger',
    },
  },

  pop: {
    label: 'Pop',
    color: 1,
    reharm: 0,
    adventurous: 0.3,
    tempo: [92, 124],
    swing: [0, 0],
    modes: [
      ['major', 4],
      ['minor', 1],
    ],
    tonics: [0, 7, 2, 9, 5, 10, 3],
    form: 'pop',
    approachChromatic: 0.2,
    templates: {
      major: {
        vamp: ['I IV', 'vi IV'],
        verse: ['I V vi IV', 'vi IV I V', 'I vi IV V', 'I iii IV IV', 'vi V IV V'],
        pre: ['IV V iii vi', 'ii iii IV V', 'IV IV V V', 'vi V IV V'],
        chorus: ['I V vi IV', 'IV I V vi', 'vi IV I V', 'IV V iii vi', 'I V IV IV', 'I III7 vi IV'],
        tag: ['IV V'],
        bridge: ['vi IV I V', 'IV iv I I', 'vi V IV V', 'bVI bVII I I'],
        riff: ['I IV'],
      },
      minor: {
        vamp: ['i bVI', 'i bVII'],
        verse: ['i bVI bIII bVII', 'i bVII bVI bVII', 'i iv bVI V7', 'i bIII bVII iv'],
        pre: ['bVI bVII bVI bVII', 'iv bVI bVII bVII'],
        chorus: ['bVI bVII i i', 'i bVI bIII bVII', 'bVI bIII bVII i', 'iv bVI bVII i'],
        tag: ['bVI bVII'],
        bridge: ['iv iv i i', 'bVI bVII bIII bIII', 'iv bVII bIII bVI'],
        riff: ['i bVII'],
      },
    },
    feels: {
      intro: 'popSoft',
      vamp: 'pop',
      verse: 'pop',
      pre: 'popBuild',
      chorus: 'fourFloor',
      bridge: 'halfTime',
      solo: 'pop',
      solo2: 'fourFloor',
      riff: 'pop',
      breakdown: 'claps',
      lift: 'build',
      outro: 'popSoft',
    },
    bassFeels: {
      intro: 'pedal',
      vamp: 'pop',
      verse: 'pop',
      pre: 'eighths',
      chorus: 'eighths',
      bridge: 'halfTime',
      solo: 'pop',
      solo2: 'eighths',
      riff: 'pop',
      breakdown: 'pop',
      lift: 'eighths',
      outro: 'pedal',
    },
    comp: { main: 'x ~ [~ x] ~', chorus: '[x x] [~ x] [x x] [~ x]', bossa: 'x ~ [~ x] ~' },
    sounds: {
      keys: 'gm_piano',
      comp2: 'strum',
      extra: 'arp',
      guitar: 'gm_acoustic_guitar_steel',
      pads: ['gm_pad_warm', 'gm_string_ensemble_1', 'gm_choir_aahs'],
      lead: ['gm_lead_6_voice', 0.32],
      double: ['gm_glockenspiel', 0.12],
      answer: ['gm_electric_guitar_clean', 0.3],
      bell: ['gm_music_box', 0.3],
      soloists: [
        ['gm_lead_2_sawtooth', 0.22],
        ['gm_electric_guitar_clean', 0.4],
      ],
      horns: ['gm_synth_brass_1', 'gm_synth_strings_1'],
      bass: 'gm_electric_bass_pick',
    },
  },

  rock: {
    label: 'Rock',
    color: 0,
    reharm: 0,
    adventurous: 0.4,
    tempo: [112, 140],
    swing: [0, 0],
    modes: [
      ['major', 3],
      ['minor', 2],
    ],
    tonics: [4, 9, 2, 7, 0],
    form: 'rock',
    approachChromatic: 0.1,
    templates: {
      major: {
        vamp: ['I bVII', 'I IV'],
        verse: ['I bVII IV I', 'I IV I V', 'I bIII IV I', 'vi IV I V', 'I I bVII IV'],
        pre: ['IV IV V V', 'ii IV V V'],
        chorus: ['I IV V IV', 'IV I V V', 'I V vi IV', 'bVI bVII I I', 'I bVII IV IV'],
        tag: ['bVI bVII'],
        bridge: ['vi IV V V', 'IV V vi vi', 'bVI bVII I I'],
        riff: ['I bVII', 'I [bVII IV]'],
      },
      minor: {
        vamp: ['i bVII', 'i bVI'],
        verse: ['i bVI bVII i', 'i bVII bVI bVII', 'i i bVI bVII', 'i iv bVII i'],
        pre: ['bVI bVI bVII bVII', 'iv iv V V'],
        chorus: ['bVI bVII i i', 'i bVI bIII bVII', 'bIII bVII i i'],
        tag: ['bVI bVII'],
        bridge: ['iv bVII bIII bVI', 'bVI bVII bVI V'],
        riff: ['i [bVII bVI]', 'i bIII'],
      },
    },
    feels: {
      intro: 'rock',
      vamp: 'rock',
      verse: 'rock',
      pre: 'rockDrive',
      chorus: 'rockDrive',
      bridge: 'halfTime',
      solo: 'rockDrive',
      solo2: 'rock',
      riff: 'rock',
      breakdown: 'halfTime',
      lift: 'build',
      outro: 'rockDrive',
    },
    bassFeels: {
      intro: 'eighths',
      vamp: 'eighths',
      verse: 'eighths',
      pre: 'eighths',
      chorus: 'eighths',
      bridge: 'halfTime',
      solo: 'eighths',
      solo2: 'eighths',
      riff: 'eighths',
      breakdown: 'halfTime',
      lift: 'eighths',
      outro: 'eighths',
    },
    comp: { main: 'x*8', chorus: 'x*8', bossa: 'x ~ x ~' },
    sounds: {
      keys: 'gm_overdriven_guitar',
      comp2: 'organ',
      extra: 'arp',
      arp: 'gm_electric_guitar_clean',
      guitar: 'gm_distortion_guitar',
      pads: ['gm_drawbar_organ', 'gm_string_ensemble_1', 'gm_choir_aahs'],
      lead: ['gm_lead_5_charang', 0.24],
      double: ['gm_overdriven_guitar', 0.14],
      answer: ['gm_distortion_guitar', 0.2],
      bell: ['gm_electric_guitar_clean', 0.3],
      soloists: [
        ['gm_distortion_guitar', 0.26],
        ['gm_overdriven_guitar', 0.32],
      ],
      horns: ['gm_overdriven_guitar', 'gm_rock_organ'],
      bass: 'gm_electric_bass_pick',
    },
  },

  jazz: {
    label: 'Jazz',
    color: 2,
    reharm: 0.7,
    adventurous: 0.7,
    tempo: [120, 160],
    swing: [0.15, 0.2],
    modes: [['major', 1]],
    tonics: [10, 3, 5, 0, 8],
    form: 'jazz',
    approachChromatic: 0.8,
    templates: {
      major: {
        vamp: ['ii7 V7', 'Imaj7 VI7'],
        verse: [
          'ii7 V7 Imaj7 VI7 ii7 V7 Imaj7 [ii7 V7]',
          'Imaj7 vi7 ii7 V7 iii7 VI7 ii7 V7',
          'Imaj7 IV7 iii7 VI7 ii7 V7 Imaj7 [ii7 V7]',
        ],
        pre: ['ii7 V7 iii7 VI7'],
        chorus: [
          'IVmaj7 iv7 iii7 VI7 ii7 V7 Imaj7 Imaj7',
          'Imaj7 I7 IVmaj7 iv7 iii7 VI7 ii7 V7',
          'iii7 VI7 ii7 V7 Imaj7 VI7 ii7 V7',
        ],
        tag: ['ii7 V7'],
        bridge: ['ii7 V7 Imaj7 Imaj7 ii7 V7 Imaj7 Imaj7', 'Imaj7 vi7 ii7 V7 Imaj7 vi7'],
        riff: ['ii7 V7'],
      },
    },
    feels: {
      intro: 'introRide',
      vamp: 'swing',
      verse: 'swing',
      pre: 'swing',
      chorus: 'swing',
      bridge: 'bossa',
      solo: 'swing',
      solo2: 'bossa',
      riff: 'swing',
      breakdown: 'introRide',
      lift: 'build',
      outro: 'introRide',
    },
    bassFeels: {
      intro: 'pedal',
      vamp: 'walking',
      verse: 'walking',
      pre: 'walking',
      chorus: 'walking',
      bridge: 'bossa',
      solo: 'walking',
      solo2: 'bossa',
      riff: 'walking',
      breakdown: 'walking',
      lift: 'walking',
      outro: 'pedal',
    },
    comp: { main: '[~ x] ~ [~ x@2] ~', chorus: '~ [~ x] ~ [x ~]', bossa: '[x ~ ~ x] [~ ~ x ~] [~ x ~ ~] [x ~ ~ ~]' },
    sounds: {
      keys: 'gm_piano',
      comp2: 'none',
      extra: 'arp',
      arp: 'gm_vibraphone',
      guitar: 'gm_electric_guitar_jazz',
      pads: ['gm_string_ensemble_1', 'gm_voice_oohs', 'gm_choir_aahs'],
      lead: ['gm_tenor_sax', 0.48],
      double: ['gm_flute', 0.12],
      answer: ['gm_muted_trumpet', 0.32],
      bell: ['gm_vibraphone', 0.3],
      soloists: [
        ['gm_tenor_sax', 0.45],
        ['gm_vibraphone', 0.42],
        ['gm_electric_guitar_jazz', 0.4],
        ['gm_trumpet', 0.36],
      ],
      horns: ['gm_trumpet', 'gm_tenor_sax'],
      bass: 'gm_acoustic_bass',
    },
  },
};

export const STYLE_NAMES = Object.keys(STYLES);
